### ISSUE TITLE
Airstrikes

### ISSUE THREAD

**Issue by dch-GH** [apetavern/sbox-grubs#294]
This feature is nearly done. Mostly just in need of art stuff.

## TODO List:
- [x] Add trail particles to plane
- [x] Add trail particles to bombs
- [x] Add an engine sound loop for the plane
- [x] Add a sound for the bomb bay doors opening
- [x] Animation that gives the plane a bit of rotational turbulence, it looks a bit static currently.
